### ISSUE TITLE
Make badge implementation more future-proof

### ISSUE THREAD

**Issue by pchote** [OpenRA/openrauseraccounts#14]
In the future I would like to add HiDPI glyph support to the UI, so we should design this in from the start.

The `openra_badges` table should rename `badge_icon` &rarr; `badge_icon16`

The profile yaml for badges should be formatted as:
```yaml
Player:
    ...
    Badges:
        Badge@0:
            Label: First Badge Label
            Icon16: http://path/to/icon.png
        Badge@1:
            Label: Second Badge Label
            Icon16: http://path/to/icon.png
```
